/**
 * @fileoverview gRPC-Web generated client stub for hello_world
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.21.12
// source: hello_world.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as hello_world_pb from './hello_world_pb';


export class HelloWorldClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorsay_hello_world = new grpcWeb.MethodDescriptor(
    '/hello_world.HelloWorld/say_hello_world',
    grpcWeb.MethodType.SERVER_STREAMING,
    hello_world_pb.HelloWorldRequest,
    hello_world_pb.HelloWorldResponse,
    (request: hello_world_pb.HelloWorldRequest) => {
      return request.serializeBinary();
    },
    hello_world_pb.HelloWorldResponse.deserializeBinary
  );

  say_hello_world(
    request: hello_world_pb.HelloWorldRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<hello_world_pb.HelloWorldResponse> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/hello_world.HelloWorld/say_hello_world',
      request,
      metadata || {},
      this.methodDescriptorsay_hello_world);
  }

}

