# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello_world.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11hello_world.proto\x12\x0bhello_world\"&\n\x11HelloWorldRequest\x12\x11\n\tuser_name\x18\x01 \x01(\t\"!\n\x11HelloWorldRespond\x12\x0c\n\x04text\x18\x01 \x01(\t2_\n\nHelloWorld\x12Q\n\x0fsay_hello_world\x12\x1e.hello_world.HelloWorldRequest\x1a\x1e.hello_world.HelloWorldRespondb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hello_world_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HELLOWORLDREQUEST._serialized_start=34
  _HELLOWORLDREQUEST._serialized_end=72
  _HELLOWORLDRESPOND._serialized_start=74
  _HELLOWORLDRESPOND._serialized_end=107
  _HELLOWORLD._serialized_start=109
  _HELLOWORLD._serialized_end=204
# @@protoc_insertion_point(module_scope)
